fileVersion: 1
id: "24"
mappingDefinitions:
  SRC:
    database: TESTING_SOURCE
    schema: SCHEMA_001
  SRC_DUMMY_TGT:
    database: ENV
    schema: ENV_TGT_1
  TARGET:
    database: TARGET
    schema: SCHEMA_003
  WORK:
    database: WRK
    schema: SCHEMA_002
name: New Environment
type: Environment
